# Generated by Django 3.1.14 on 2026-01-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personal_info_photos/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='height',
            field=models.CharField(blank=True, help_text='e.g., 5\'8" or 173 cm', max_length=50),
        ),
    ]
