# Generated by Django 3.1.14 on 2026-01-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20260125_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_code',
            field=models.CharField(default='+1', max_length=10),
        ),
    ]
